services:
  app:
    build:
      context: app
    container_name: background-check-app
    restart: no
    image: background-check-app
    env_file:
      - path: /.env
        required: false
    stdin_open: true # docker run -i
    tty: true        # docker run -t

